version: '2'

services:
  mock-server:
    container_name: mock-server
    image: quay.io/keboola/ex-generic-mock-server
    tty: true
    stdin_open: true
    ports:
      - "8888:80"
    volumes:
        - ./examples:/examples/
    environment:
        - KBC_EXAMPLES_DIR=/examples/

  mock-server-behind-proxy:
      container_name: mock-server-behind-proxy
      image: quay.io/keboola/ex-generic-mock-server
      tty: true
      stdin_open: true
      ports:
        - "8889:80"
      volumes:
          - ./examples:/examples/
      environment:
          - KBC_EXAMPLES_DIR=/examples/

  mock-server-https-self-signed-proxy:
    image: outrigger/https-proxy:1.0
    volumes:
      - ./examples/141-https-self-signed/https/ca:/etc/nginx/ca
      - ./examples/141-https-self-signed/https/certs:/etc/nginx/certs
    environment:
      UPSTREAM_DOMAIN: mock-server
      UPSTREAM_PORT: 80
      PROXY_DOMAIN: mock-server-https-self-signed-proxy

  mock-server-https-client-cert-proxy:
    image: outrigger/https-proxy:1.0
    volumes:
      - ./examples/142-https-client-cert/https/ca:/etc/nginx/ca
      - ./examples/142-https-client-cert/https/certs:/etc/nginx/certs
      - ./examples/142-https-client-cert/https/client_ca:/etc/nginx/client_ca
      - ./examples/142-https-client-cert/https/nginx.conf.tmpl:/etc/confd/templates/nginx.conf.tmpl
    environment:
      UPSTREAM_DOMAIN: mock-server
      UPSTREAM_PORT: 80
      PROXY_DOMAIN: mock-server-https-client-cert-proxy

  ssh-proxy:
      build:
        context: ..
        dockerfile: Dockerfile-ssh-proxy
      ports:
        - "2222:22"
      links:
        - mock-server-behind-proxy

  extractor:
    build: ..
    image: keboola/generic-extractor
    volumes:
      - .tmp:/tmp
      - ./examples/:/examples/
    tty: true
    stdin_open: true
    command:
      - /bin/sh
      - -c
      - "php /code/run.php --data=/examples/$$KBC_EXAMPLE_NAME"
    links:
      - mock-server
      - mock-server-https-self-signed-proxy
      - mock-server-https-client-cert-proxy
      - ssh-proxy
