#!/bin/bash
set -e

run_example() {
    if [ -z "$1" ] ; then
        printf "No example name provided."
        exit 1
    else
        printf "\nRunning example $1\n"
    fi
    EXAMPLE_NAME=$1
    rm -rf examples/$1/out/*
    mkdir -p examples/$1/out/tables/
    docker-compose run --rm -e "KBC_EXAMPLE_NAME=$EXAMPLE_NAME" extractor
    if diff --brief --recursive examples/${EXAMPLE_NAME}/out/tables/ examples/${EXAMPLE_NAME}/_sample_out/ ; then
        printf "Example $EXAMPLE_NAME successful.\n"
    else
        printf "Example $EXAMPLE_NAME failed.\n"
        diff --recursive examples/${EXAMPLE_NAME}/out/tables/ examples/${EXAMPLE_NAME}/_sample_out/
    fi
}

# Start mock server
docker-compose build --force-rm --pull

# Run examples
run_example "001-simple-job"
run_example "002-array-in-object"
run_example "003-multiple-arrays-in-object"
run_example "004-array-in-nested-object"
run_example "005-two-arrays-in-nested-object"
run_example "006-simple-object"
run_example "007-nested-object"
run_example "008-single-object-in-array"
run_example "009-nested-array"
run_example "010-object-with-nested-array"
run_example "011-object-with-nested-object"
run_example "012-deeply-nested-object"
run_example "013-skip-flatten"
run_example "014-skip-flatten-nested"
run_example "015-skip-boolean"
run_example "016-inconsistent-object"
run_example "017-upgrading-array"
run_example "018-multiple-filters"
run_example "019-different-delimiter"
run_example "020-setting-delimiter-complex"
run_example "021-basic-child-job"
run_example "022-basic-child-job-datatype"
run_example "023-child-job-nested-id"
run_example "024-child-job-deeply-nested-id"
run_example "025-naming-conflict"
run_example "026-basic-deeper-nesting"
run_example "027-basic-deeper-nesting-alternative"
run_example "028-advanced-deep-nesting"
run_example "029-simple-filter"
run_example "030-not-like-filter"
run_example "031-combined-filter"
run_example "032-multiple-combined-filter"
run_example "033-job-parameters"
run_example "034-post-request"
run_example "035-complex-post"
run_example "036-complex-get"
run_example "037-retry-header"
run_example "038-default-headers"
run_example "039-default-parameters"
run_example "040-required-headers"
run_example "041-paging-stop-same"
run_example "042-paging-stop-same-2"
run_example "043-paging-stop-underflow"
run_example "044-paging-stop-underflow-struct"
run_example "045-next-page-flag-has-more"
run_example "046-next-page-flag-has-more-2"
run_example "047-next-page-flag-is-last"
run_example "048-force-stop"
run_example "049-pagination-offset-rename"
run_example "050-pagination-offset-override"
run_example "051-pagination-pagenum-basic"
run_example "052-pagination-pagenum-rename"
run_example "053-pagination-pagenum-override"
run_example "054-pagination-response-url-basic"
run_example "055-pagination-response-url-params"
run_example "056-pagination-response-url-params-override"
run_example "057-pagination-response-param-basic"
run_example "058-pagination-response-param-override"
run_example "059-pagination-response-param-scroll-request"
run_example "060-pagination-cursor-basic"
run_example "061-pagination-cursor-reverse"
run_example "062-pagination-multiple-scrollers"
run_example "063-mapping-automatic"
run_example "064-mapping-basic"
run_example "065-mapping-child-jobs"
run_example "066-mapping-tables-basic"
run_example "067-mapping-tables-nested"
run_example "068-mapping-tables-nested-array"
run_example "069-mapping-tables-nested-direct"
run_example "070-mapping-tables-nested-direct-pk"
run_example "071-mapping-multiple-pk"
run_example "072-mapping-pk-disable"
run_example "073-mapping-forceType"
run_example "074-http-headers"
run_example "075-incremental-output"
run_example "076-user-data"
run_example "077-query-auth"
run_example "078-basic-auth"
run_example "079-login-auth-headers"
run_example "080-login-auth-query"
run_example "081-login-auth-headers-query-override"
run_example "082-login-auth-expires"
run_example "083-login-auth-expires-date"
run_example "084-login-auth-expires-seconds"
run_example "085-function-job-placeholders"
run_example "086-function-job-placeholders-reference"
run_example "087-function-baseurl"
run_example "088-function-baseurl-sprintf"
run_example "089-function-job-parameters-md5"
run_example "090-function-job-parameters-sha1"
# run_example "091-function-user-data" # -> This is not testable, because it uses currentStart
run_example "092-function-user-date-set-date"
run_example "093-function-api-http-headers"
run_example "094-function-config-headers"
run_example "095-function-nested"
run_example "096-function-nested-from-to"
run_example "097-function-ifempty"
run_example "098-function-hmac"
run_example "099-function-query-parameters"
run_example "100-function-login-headers"
run_example "101-function-query-auth"
# run_example "102-oauth1" # -> This is not testable, because it uses random hash
run_example "103-oauth2-bearer"
# run_example "104-oauth2-hmac" # -> This is not testable, because it uses random hash
run_example "105-oauth2-login"
run_example "106-child-jobs-array"
run_example "107-incremental-load"
run_example "108-incremental-load-date"
# run_example "109-incremental-load-from-to" # -> This is not testable, because it uses currentStart
# run_example "110-incremental-relative" # -> This is not testable, because it uses currentStart
run_example "111-templates-example"
run_example "112-iterations-params"
run_example "113-iterations-headers"
run_example "114-oauth2-google"
run_example "115-multiple-pk-parent"
run_example "116-multiple-conditions-multiple-jobs"
run_example "117-function-login-params-response"
run_example "118-function-login-headers-response"
run_example "119-function-nested-config"
run_example "120-datafield-separator"
run_example "121-inconsistent-object-legacy"
run_example "122-multiple-filters-legacy"
run_example "123-incremental-load-legacy"
run_example "124-naming-conflict-legacy"
run_example "125-user-data-legacy"
run_example "126-pagination-stop-limit"
run_example "127-pagination-stop-field"
run_example "128-login-auth-text"
run_example "129-login-auth-scalar"
run_example "130-unsupported-nested-array"
run_example "131-ssh-tunnel"
run_example "132-ignore-errors"
run_example "133-ssh-tunnel-iterations-params"
run_example "134-user-data-in-mapping"
run_example "135-basic-child-job-array"
run_example "136-post-request-functions"
run_example "137-mapping-tables-nested-empty"
run_example "138-pagination-stop-field-child-filter"
run_example "139-pagination-hasmore-child-filter"
run_example "140-pagination-forcestop-child-filter"
run_example "141-https-self-signed"

# Stop mock server
printf "\nAll examples successfull.\n"
docker stop mock-server
