services:
  # for development purposes
  dev:
    build: .
    volumes:
        - ./:/code
        - ./data:/data
        - ../docker/keys:/code/keys
    environment:
      - KBC_DATADIR=./data
  test:
    # Use to run flake8 and unittests checks
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_DATADIR=./data
    command:
      - /bin/sh
      - /code/scripts/build_n_test.sh

  test-calls:
    # Run examples against mock server
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    command: python /code/tests/_test_calls.py
    links:
      - mock-server
  mock-server:
    container_name: mock-server
    image: quay.io/keboola/ex-generic-mock-server:latest
    tty: true
    stdin_open: true
    ports:
      - 8888:80
    volumes:
      - ./tests/calls:/examples/
    environment:
      - KBC_EXAMPLES_DIR=/examples/

  # i was about to create a common network with the generic-extractor compose file
  # to avoid duplication, but that would create an unnecessary dependency
  server.local:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../docker/keys/server.crt:/etc/nginx/server.crt
      - ../docker/keys/server.key:/etc/nginx/server.key
      - ../docker/keys/rootCA.crt:/etc/nginx/ca.crt
